export enum MessageType {
  SELF_ID = 'SELF_ID',
  BASIC_ID = 'BASIC_ID',
  LOCATION = 'LOCATION',
  OPERATOR_ID = 'OPERATOR_ID',
  AUTH = 'AUTH',
  SYSTEM = 'SYSTEM',
  MESSAGE_PACK = 'MESSAGE_PACK',
  NOT_DEFINED = 'NOT_DEFINED',
}
